version: '3'

services:
  nginx:
    # TODO: add script for rebuild nginx conf. without restart container
    #       see /docker-entrypoint.sh
    image: nginx:alpine
    restart: unless-stopped
    env_file:
      - ./config/env/nginx.env
    volumes:
      - ./data/nginx/templates:/etc/nginx/templates:ro
      - ./log/nginx:/var/log/nginx:rw
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bot
    command: "/bin/sh -c '/docker-entrypoint.sh nginx -g \"daemon off;\"; while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\";'"
    networks:
      - bot_nw
      - user_nw
    
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:rw
      - ./data/certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  bot:
    build: ../bot-service
    restart: unless-stopped
    env_file:
      - ./config/env/bot.env
      - ./config/env/pgsql_bot.env
      - ./config/env/redis_auth.env
      - ./config/env/redis_bot.env
    volumes:
      - ../bot-service:/app:rw
      - /root/go/pkg/mod/cache:/go/pkg/mod/cache:rw
    tty: true
    networks:
      - bot_nw
      - redis_auth_nw
  
  pgsql_bot:
    image: postgres:15.1-alpine
    restart: unless-stopped
    env_file:
      - ./config/env/pgsql_bot.env
    volumes: 
      - ./data/pgsql_bot/pginit:/docker-entrypoint-initdb.d:rw
      - ./data/pgsql_bot/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "5431:5432"
    networks:
      - bot_nw

  user:
    build: ../user-service
    restart: unless-stopped
    volumes:
      - ../user-service:/app:rw
      - /root/go/pkg/mod/cache:/go/pkg/mod/cache:rw
    tty: false
    command: go run ./cmd/server.go
    networks:
      - user_nw
      - redis_auth_nw

  pgsql_user:
    image: postgres:15.1-alpine
    restart: unless-stopped
    env_file:
      - ./config/env/pgsql_user.env
    volumes: 
      - ./data/pgsql_user/pginit:/docker-entrypoint-initdb.d:rw
      - ./data/pgsql_user/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "5430:5432"
    networks:
      - user_nw

  redis_auth: 
    image: redis:7.0.5-alpine
    command: redis-server
    volumes:
    - ./data/redis_auth/redis_data:/var/lib/redis:rw
    - ./config/redis_auth/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - redis_auth_nw
  
  redis_bot: 
    image: redis:7.0.5-alpine
    command: redis-server
    volumes:
    - ./data/redis_bot/redis_data:/var/lib/redis:rw
    - ./config/redis_bot/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - bot_nw

networks:
  bot_nw:
  user_nw:
  redis_auth_nw: